### ISSUE TITLE
When i cmake opencv4.4(with cuda),raised some errors

### ISSUE THREAD

**Issue by SugarMuzi** [vsamy/eigen-cddlib#13]
the error as follow:
-- Detected processor: x86_64
-- Looking for ccache - not found
-- Found ZLIB: /lib64/libz.so (found suitable version "1.2.7", minimum required is "1.2.3")
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- libjpeg-turbo: VERSION = 2.0.5, BUILD = opencv-4.4.0-libjpeg-turbo
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)
-- Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1)
-- Could NOT find Jasper (missing: JASPER_LIBRARIES JASPER_INCLUDE_DIR)
-- Found ZLIB: /lib64/libz.so (found version "1.2.7")
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Checking for module 'gtk+-2.0'
--   No package 'gtk+-2.0' found
-- Checking for module 'gtkglext-1.0'
--   No package 'gtkglext-1.0' found
-- found Intel IPP (ICV version): 2020.0.0 [2020.0.0 Gold]
-- at: /data1/yaoning.li/app/src/opencv/build/3rdparty/ippicv/ippicv_lnx/icv
-- found Intel IPP Integration Wrappers sources: 2020.0.0
-- at: /data1/yaoning.li/app/src/opencv/build/3rdparty/ippicv/ippicv_lnx/iw
-- Could NOT find CUDNN: Found unsuitable version "..10", but required is at least "7.5" (found /data1/yaoning.li/cuda/lib64/libcudnn.so)
-- CUDA detected: 10.2
-- CUDA NVCC target flags: -D_FORCE_INLINES
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /lib64/libopenblas.so
-- LAPACK(OpenBLAS): Support is enabled.
-- OpenCV Python: during development append to PYTHONPATH: /data1/yaoning.li/app/src/opencv/build/python_loader
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
-- Checking for module 'libdc1394-2'
--   No package 'libdc1394-2' found
-- Caffe:   NO
-- Protobuf:   NO
-- Glog:   YES
-- Checking for module 'freetype2'
--   No package 'freetype2' found
-- Checking for module 'harfbuzz'
--   No package 'harfbuzz' found
-- freetype2:   NO
-- harfbuzz:    NO
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Julia not found. Not compiling Julia Bindings.
-- Module opencv_ovis disabled because OGRE3D was not found
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.0
-- Checking SFM deps... TRUE
-- CERES support is disabled. Ceres Solver for reconstruction API is required.
-- Checking for module 'tesseract'
--   No package 'tesseract' found
-- Tesseract:   NO
-- Allocator metrics storage type: 'long long'
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.0
-- Checking SFM deps... TRUE
-- CERES support is disabled. Ceres Solver for reconstruction API is required.
--
-- General configuration for OpenCV 4.4.0 =====================================
--   Version control:               unknown
--
--   Extra modules:
--     Location (extra):            /data1/yaoning.li/app/src/opencv_contrib/modules
--     Version control (extra):     unknown
--
--   Platform:
--     Timestamp:                   2023-03-01T08:07:14Z
--     Host:                        Linux 3.10.0-514.16.1.el7.x86_64 x86_64
--     CMake:                       3.17.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/gmake
--     Configuration:               RELEASE
--
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
--       SSE4_1 (15 files):         + SSSE3 SSE4_1
--       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (3 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (28 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
--       AVX512_SKX (3 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
--
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ standard:                11
--     C++ Compiler:                /data1/yaoning.li/gcc/bin/c++  (ver 7.5.0)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /data1/yaoning.li/gcc/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed
--     Linker flags (Debug):        -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          m pthread cudart_static dl rt nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cufft -L/data1/yaoning.li/cuda/lib64 -L/lib64
--     3rdparty dependencies:
--
--   OpenCV modules:
--     To be built:                 alphamat calib3d core cudaarithm cudabgsegm cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor ml objdetect optflow phase_unwrapping photo plot quality rapid sfm shape stitching structured_light superres surface_matching video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
--     Disabled:                    aruco bgsegm bioinspired ccalib cudacodec datasets dnn dnn_objdetect dnn_superres dpm face hdf python2 reg rgbd saliency stereo text tracking world
--     Disabled by dependency:      -
--     Unavailable:                 cnn_3dobj cvv freetype java js julia matlab ovis python3 ts viz
--     Applications:                apps
--     Documentation:               NO
--     Non-free algorithms:         YES
--
--   GUI:
--     GTK+:                        NO
--     OpenGL support:              NO
--
--   Media I/O:
--     ZLib:                        /lib64/libz.so (ver 1.2.7)
--     JPEG:                        libjpeg-turbo (ver 2.0.5-62)
--     WEBP:                        build (ver encoder: 0x020f)
--     PNG:                         build (ver 1.6.37)
--     TIFF:                        build (ver 42 - 4.0.10)
--     JPEG 2000:                   build Jasper (ver 1.900.1)
--     OpenEXR:                     build (ver 2.3.0)
--     GDAL:                        NO
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
--
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      YES
--       avcodec:                   YES (56.26.100)
--       avformat:                  YES (56.25.101)
--       avutil:                    YES (54.20.100)
--       swscale:                   YES (3.1.101)
--       avresample:                YES (2.1.0)
--     GStreamer:                   NO
--     v4l/v4l2:                    YES (linux/videodev2.h)
--     Xine:                        NO
--
--   Parallel framework:            pthreads
--
--   Trace:                         YES (with Intel ITT)
--
--   Other third-party libraries:
--     Intel IPP:                   2020.0.0 Gold [2020.0.0]
--            at:                   /data1/yaoning.li/app/src/opencv/build/3rdparty/ippicv/ippicv_lnx/icv
--     Intel IPP IW:                sources (2020.0.0)
--               at:                /data1/yaoning.li/app/src/opencv/build/3rdparty/ippicv/ippicv_lnx/iw
--     Lapack:                      YES (/lib64/libopenblas.so)
--     Eigen:                       YES (ver 3.4.0)
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
--
--   NVIDIA CUDA:                   YES (ver 10.2, CUFFT CUBLAS FAST_MATH)
--     NVIDIA GPU arch:
--     NVIDIA PTX archs:
--
--   cuDNN:                         NO
--
--   OpenCL:                        YES (no extra features)
--     Include path:                /data1/yaoning.li/app/src/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
--
--   Python (for build):            /data1/yaoning.li/anaconda3/envs/mmlab/bin/python
--
--   Install to:                    /data1/yaoning.li/app
-- -----------------------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /data1/yaoning.li/app/src/opencv/build
[  0%] Built target gen-pkgconfig
[  0%] Built target ittnotify
[  1%] Built target quirc
[  1%] Built target opencv_videoio_plugins
[  3%] Built target libjasper
[  5%] Built target libpng
[  5%] Built target numeric
[  8%] Built target ippiw
[ 13%] Built target libtiff
[ 16%] Built target libjpeg-turbo
[ 17%] Built target ade
[ 25%] Built target libwebp
[ 25%] Built target opencv_cudev
[ 30%] Built target libprotobuf
[ 38%] Built target IlmImf
[ 39%] Built target multiview
[ 39%] Built target correspondence
[ 47%] Built target opencv_core
[ 47%] Built target opencv_version
[ 48%] Built target opencv_flann
[ 49%] Built target opencv_ml
[ 50%] Built target opencv_surface_matching
[ 53%] Built target opencv_cudaarithm
[ 60%] Built target opencv_imgproc
[ 60%] Built target opencv_quality
[ 60%] Built target opencv_phase_unwrapping
[ 60%] Building CXX object modules/intensity_transform/CMakeFiles/opencv_intensity_transform.dir/src/bimef.cpp.o
[ 60%] Built target opencv_plot
[ 60%] Built target opencv_img_hash
[ 61%] Built target opencv_alphamat
[ 61%] Built target opencv_hfs
[ 61%] Built target opencv_fuzzy
[ 62%] Built target opencv_cudawarping
[ 64%] Built target opencv_imgcodecs
[ 66%] Built target opencv_features2d
[ 67%] Built target opencv_line_descriptor
[ 69%] Built target opencv_cudafilters
[ 70%] Built target opencv_videoio
[ 71%] Built target opencv_highgui
[ 71%] Built target opencv_annotation
[ 71%] Built target opencv_visualisation
[ 72%] Built target opencv_cudafeatures2d
[ 74%] Built target opencv_calib3d
[ 75%] Built target opencv_rapid
[ 75%] Built target opencv_interactive-calibration
[ 75%] Built target opencv_structured_light
[ 76%] Built target opencv_cudastereo
[ 77%] Built target opencv_objdetect
[ 78%] Built target opencv_shape
[ 79%] Built target opencv_video
[ 80%] Built target opencv_xobjdetect
[ 83%] Built target opencv_cudaimgproc
Scanning dependencies of target opencv_gapi
Scanning dependencies of target opencv_waldboost_detector
[ 83%] Linking CXX shared library ../../lib/libopencv_cudabgsegm.so
[ 83%] Building CXX object modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/waldboost_detector.cpp.o
[ 83%] Linking CXX shared library ../../lib/libopencv_cudalegacy.so
[ 83%] Linking CXX shared library ../../lib/libopencv_photo.so
[ 83%] Linking CXX shared library ../../lib/libopencv_xfeatures2d.so
[ 83%] Built target opencv_cudabgsegm
[ 86%] Built target opencv_ximgproc
[ 86%] Processing OpenCL kernels (optflow)
Scanning dependencies of target opencv_optflow
[ 87%] Built target opencv_cudalegacy
[ 88%] Built target opencv_photo
[ 88%] Building NVCC (Device) object modules/cudaobjdetect/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_lbp.cu.o
[ 89%] Building NVCC (Device) object modules/cudaobjdetect/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_hog.cu.o
Scanning dependencies of target opencv_xphoto
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gmat.cpp.o
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gorigin.cpp.o
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/garray.cpp.o
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gkernel.cpp.o
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gscalar.cpp.o
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gopaque.cpp.o
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gproto.cpp.o
[ 89%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gnode.cpp.o
[ 90%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gbackend.cpp.o
[ 90%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/bm3d_image_denoising.cpp.o
[ 92%] Built target opencv_xfeatures2d
[ 92%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/dct_image_denoising.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/deepflow.cpp.o
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp: In function ‘cv::Mat cv::intensity_transform::solveLinearEquation(const cv::Mat_<float>&, cv::Mat_<float>&, cv::Mat_<float>&, float)’:
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:136:17: error: ‘Index’ is not a member of ‘Eigen’
     for (Eigen::Index i = 0; i < tempx.rows(); i++)
                 ^~~~~
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:136:30: error: ‘i’ was not declared in this scope
     for (Eigen::Index i = 0; i < tempx.rows(); i++)
                              ^
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:145:17: error: ‘Index’ is not a member of ‘Eigen’
     for (Eigen::Index j = 0; j < tempy.cols(); j++)
                 ^~~~~
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:145:30: error: ‘j’ was not declared in this scope
     for (Eigen::Index j = 0; j < tempy.cols(); j++)
                              ^
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:145:30: note: suggested alternative: ‘jn’
     for (Eigen::Index j = 0; j < tempy.cols(); j++)
                              ^
                              jn
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:158:17: error: ‘Index’ is not a member of ‘Eigen’
     for (Eigen::Index j = 0; j < W_h.cols(); j++)
                 ^~~~~
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:158:30: error: ‘j’ was not declared in this scope
     for (Eigen::Index j = 0; j < W_h.cols(); j++)
                              ^
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:158:30: note: suggested alternative: ‘jn’
     for (Eigen::Index j = 0; j < W_h.cols(); j++)
                              ^
                              jn
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:160:21: error: ‘Index’ is not a member of ‘Eigen’
         for (Eigen::Index i = 0; i < W_h.rows(); i++)
                     ^~~~~
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:160:34: error: ‘i’ was not declared in this scope
         for (Eigen::Index i = 0; i < W_h.rows(); i++)
                                  ^
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:185:17: error: ‘Index’ is not a member of ‘Eigen’
     for (Eigen::Index j = 0; j < tempx.cols(); j++)
                 ^~~~~
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:185:30: error: ‘j’ was not declared in this scope
     for (Eigen::Index j = 0; j < tempx.cols(); j++)
                              ^
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:185:30: note: suggested alternative: ‘jn’
     for (Eigen::Index j = 0; j < tempx.cols(); j++)
                              ^
                              jn
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:187:21: error: ‘Index’ is not a member of ‘Eigen’
         for (Eigen::Index i = 0; i < tempx.rows(); i++)
                     ^~~~~
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:187:34: error: ‘i’ was not declared in this scope
         for (Eigen::Index i = 0; i < tempx.rows(); i++)
                                  ^
[ 92%] Linking CXX executable ../../../../bin/opencv_waldboost_detector
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:221:92: error: ‘IncompleteCholesky’ is not a member of ‘Eigen’
     Eigen::ConjugateGradient<Eigen::SparseMatrix<float>, Eigen::Lower|Eigen::Upper, Eigen::IncompleteCholesky<float> > cg;
                                                                                            ^~~~~~~~~~~~~~~~~~
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:221:92: note: suggested alternative: ‘IncompleteLUT’
     Eigen::ConjugateGradient<Eigen::SparseMatrix<float>, Eigen::Lower|Eigen::Upper, Eigen::IncompleteCholesky<float> > cg;
                                                                                            ^~~~~~~~~~~~~~~~~~
                                                                                            IncompleteLUT
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:221:92: error: ‘IncompleteCholesky’ is not a member of ‘Eigen’
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:221:92: note: suggested alternative: ‘IncompleteLUT’
     Eigen::ConjugateGradient<Eigen::SparseMatrix<float>, Eigen::Lower|Eigen::Upper, Eigen::IncompleteCholesky<float> > cg;
                                                                                            ^~~~~~~~~~~~~~~~~~
                                                                                            IncompleteLUT
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:221:116: error: template argument 3 is invalid
     Eigen::ConjugateGradient<Eigen::SparseMatrix<float>, Eigen::Lower|Eigen::Upper, Eigen::IncompleteCholesky<float> > cg;
                                                                                                                    ^
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:221:118: error: expected unqualified-id before ‘>’ token
     Eigen::ConjugateGradient<Eigen::SparseMatrix<float>, Eigen::Lower|Eigen::Upper, Eigen::IncompleteCholesky<float> > cg;
                                                                                                                      ^
/data1/yaoning.li/app/src/opencv_contrib/modules/intensity_transform/src/bimef.cpp:222:5: error: ‘cg’ was not declared in this scope
     cg.setTolerance(0.1f);
     ^~
[ 92%] Built target opencv_waldboost_detector
[ 92%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/grayworld_white_balance.cpp.o
make[2]: *** [modules/intensity_transform/CMakeFiles/opencv_intensity_transform.dir/src/bimef.cpp.o] Error 1
make[1]: *** [modules/intensity_transform/CMakeFiles/opencv_intensity_transform.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 92%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/learning_based_color_balance.cpp.o
[ 92%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/inpainting.cpp.o
[ 92%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/oilpainting.cpp.o
[ 92%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/simple_color_balance.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gcall.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/interfaces.cpp.o
[ 92%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/tonemap.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/gcomputation.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/motempl.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/pcaflow.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/rlof/geo_interpolation.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/operators.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/rlof/rlof_localflow.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/rlofflow.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/simpleflow.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/sparse_matching_gpc.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/kernels_core.cpp.o
Scanning dependencies of target opencv_cudaobjdetect
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/kernels_imgproc.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/sparsetodenseflow.cpp.o
[ 92%] Building CXX object modules/cudaobjdetect/CMakeFiles/opencv_cudaobjdetect.dir/src/cascadeclassifier.cpp.o
[ 92%] Building CXX object modules/cudaobjdetect/CMakeFiles/opencv_cudaobjdetect.dir/src/hog.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/src/tvl1flow.cpp.o
[ 92%] Building CXX object modules/optflow/CMakeFiles/opencv_optflow.dir/opencl_kernels_optflow.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/kernels_video.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/render.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/render_ocv.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/ginfer.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/ft_render.cpp.o
[ 92%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/gmodel.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/gmodelbuilder.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/gislandmodel.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/gcompiler.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/gcompiled.cpp.o
[ 93%] Linking CXX shared library ../../lib/libopencv_cudaobjdetect.so
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/gstreaming.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/helpers.cpp.o
[ 93%] Built target opencv_cudaobjdetect
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/dump_dot.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/islands.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/meta.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/kernels.cpp.o
[ 93%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/exec.cpp.o
[ 94%] Linking CXX shared library ../../lib/libopencv_optflow.so
[ 94%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/transformations.cpp.o
[ 94%] Built target opencv_optflow
[ 94%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/pattern_matching.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/perform_substitution.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/passes/streaming.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/executor/gexecutor.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/executor/gstreamingexecutor.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/executor/gasync.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/cpu/gcpubackend.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/cpu/gcpukernel.cpp.o
[ 95%] Linking CXX shared library ../../lib/libopencv_xphoto.so
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/cpu/gcpuimgproc.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/cpu/gcpuvideo.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/cpu/gcpucore.cpp.o
[ 95%] Built target opencv_xphoto
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/fluid/gfluidbuffer.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/fluid/gfluidbackend.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/fluid/gfluidimgproc.cpp.o
[ 95%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/fluid/gfluidimgproc_func.dispatch.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/fluid/gfluidcore.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ocl/goclbackend.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ocl/goclkernel.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ocl/goclimgproc.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ocl/goclcore.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ie/giebackend.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ie/giebackend/giewrapper.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/render/grenderocvbackend.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/render/grenderocv.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/plaidml/gplaidmlcore.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/plaidml/gplaidmlbackend.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/common/gcompoundbackend.cpp.o
[ 96%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/common/gcompoundkernel.cpp.o
[ 97%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/s11n.cpp.o
[ 97%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/common/serialization.cpp.o
[ 97%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/backends/fluid/gfluidimgproc_func.sse4_1.cpp.o
[ 97%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/backends/fluid/gfluidimgproc_func.avx2.cpp.o
[ 97%] Linking CXX shared library ../../lib/libopencv_gapi.so
[ 97%] Built target opencv_gapi
make: *** [all] Error 2

my eigen version is 3.4.0,and opencv version is 4.4.0

**Comment by vsamy** [comment]
This is an issue with opencv not eigen-cddlib
